[package]
name = "warp_square_engine"
version = "0.3.0"
edition = "2021"

[workspace]
members = [
    "python",
    "java",
]

[workspace.package]
version = "0.3.0"
edition = "2021"

[dependencies]
bitflags = "2.4.1"
pyo3 = "0.19.0"
